Repository djx-community/love-verse, pull requests merged in 2024-02, with the labels that each got.

#1 Implement basic functionality
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/Craft bespoke L🤍ve poems.png
  src/assets/Group 8.png
  src/assets/LoVerse.png
  src/assets/backgrounds/black-red.jpg
  src/assets/backgrounds/dark-blue-black.jpg
  src/assets/backgrounds/dark-read-heart.jpg
  src/assets/backgrounds/light-black.jpg
  src/assets/backgrounds/light-red-heart.jpg
  src/assets/backgrounds/orange-black.jpeg
  src/assets/backgrounds/red-white.jpg
  src/assets/backgrounds/sky-blue-pink.jpg
  src/assets/backgrounds/white-red.jpg
  src/assets/copy.svg
  src/assets/download.svg
  src/assets/logo.png
  src/components/FormComponent.tsx
  src/components/card/StoryImageCard.css
  src/components/card/StoryImageCard.tsx
  src/components/carousel/Carousel.css
  src/components/carousel/Carousel.tsx
  src/components/carousel/Helper.tsx
  src/index.css
  src/main.tsx
  src/pages/PageNotFound.tsx
  src/pages/PagePreview.tsx
  src/services/Helper.ts
  src/services/Services.ts
Labels: documentation, enhancement

#5 feat: Implement form validation
  src/components/FormComponent.tsx
  src/components/form/FormComponent.tsx
  src/components/form/Helper.ts
  src/pages/PageHome.tsx
Labels: enhancement

#7 Changes
  index.html
  src/components/card/StoryImageCard.tsx
  src/components/carousel/Carousel.tsx
  src/components/carousel/Helper.tsx
  src/components/form/FormComponent.tsx
  src/pages/PagePreview.tsx
Labels: bug, enhancement

#10 small tweaks
  src/components/form/FormComponent.css
  src/components/form/FormComponent.tsx
  src/index.css
Labels: enhancement
